version: "3.8"
services:
  inference-service:
    build:
      context: .
      dockerfile: service/Dockerfile
    image: imageaivsreal/service:local
    env_file:
      - .env
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - HUGGINGFACE_HUB_TOKEN=${HF_TOKEN}
    ports:
      - "50051:50051"
    # volumes:
    #   - ./hf_cache:/root/.cache/huggingface   
    command: ["/opt/venv/bin/python", "-u", "service/inference_server.py"]