apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubermatic-dl-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-classifier
  template:
    metadata:
      labels:
        app: image-classifier
    spec:
      containers:
      - name: classifier-container
        image: <TU_USUARIO_DOCKER>/image-classifier:v1
        ports:
        - containerPort: 80